###### Repository/Build Configurations ######
app_location: "/"         # Where your index.html is
api_location: ""          
output_location: ""       
skip_app_build: true      # ADD THIS LINE
###### End of Repository/Build Configurations ######
